name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2] # Usa 2 instâncias paralelas
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Start Server
              run: npm start # Inicia o servidor

            - name: Wait for Server
              run: npx wait-on http://localhost:3000 # Aguarda o servidor

            - name: Cypress run
              uses: cypress-io/github-action@v7
              with:
                  record: true
                  parallel: true
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
